//go:build ignore

// gen.go generates TypeToString from the miekg/dns module (BSD-3-Clause),
// which sing-box uses to parse and format DNS query types.
// DNS types are assigned by IANA and only get added, so the latest version is used by default.
//
// The module is downloaded from the Go module proxy and verified by the checksum database,
// then the table is collected in the same way as miekg/dns types_generate.go,
// so it does not depend on the file layout of miekg/dns.
// https://github.com/miekg/dns/blob/master/types_generate.go
package main

import (
	"archive/zip"
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/constant"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"io"
	"log"
	"maps"
	"net/http"
	"os"
	"path"
	"slices"
	"strings"
)

const (
	modulePath  = "github.com/miekg/dns"
	packageName = "dns"
	proxyURL    = "https://proxy.golang.org"
	sumDBURL    = "https://sum.golang.org"
)

func main() {
	version := flag.String("version", "latest", "miekg/dns version")
	output := flag.String("output", "querytype_gen.go", "output file")
	flag.Parse()
	if *version == "latest" {
		latest, err := latestVersion()
		if err != nil {
			log.Fatal(err)
		}
		*version = latest
	}

	data, err := download(fmt.Sprintf("%s/%s/@v/%s.zip", proxyURL, modulePath, *version))
	if err != nil {
		log.Fatal(err)
	}
	err = verifyZip(data, *version)
	if err != nil {
		log.Fatal(err)
	}
	fileSet := token.NewFileSet()
	files, err := parsePackage(fileSet, data, *version)
	if err != nil {
		log.Fatal(err)
	}
	table, err := collectTypes(fileSet, files)
	if err != nil {
		log.Fatal(err)
	}

	var buffer bytes.Buffer
	fmt.Fprintf(&buffer, "// Code generated by gen.go from %s@%s; DO NOT EDIT.\n\n", modulePath, *version)
	fmt.Fprintf(&buffer, "package singdns\n\n")
	fmt.Fprintf(&buffer, "var TypeToString = map[uint16]string{\n")
	for _, value := range slices.Sorted(maps.Keys(table)) {
		fmt.Fprintf(&buffer, "%d: %q,\n", value, table[value])
	}
	fmt.Fprintf(&buffer, "}\n")
	source, err := format.Source(buffer.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	err = os.WriteFile(*output, source, 0o644)
	if err != nil {
		log.Fatal(err)
	}
}

func download(url string) ([]byte, error) {
	response, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download %s: %s", url, response.Status)
	}
	return io.ReadAll(response.Body)
}

func latestVersion() (string, error) {
	data, err := download(fmt.Sprintf("%s/%s/@latest", proxyURL, modulePath))
	if err != nil {
		return "", err
	}
	var info struct{ Version string }
	err = json.Unmarshal(data, &info)
	if err != nil {
		return "", err
	}
	if info.Version == "" {
		return "", fmt.Errorf("latest version of %s not found", modulePath)
	}
	return info.Version, nil
}

// verifyZip checks the module zip against the hash in the checksum database,
// the hash is computed in the same way as golang.org/x/mod/sumdb/dirhash.Hash1.
func verifyZip(data []byte, version string) error {
	lookup, err := download(fmt.Sprintf("%s/lookup/%s@%s", sumDBURL, modulePath, version))
	if err != nil {
		return err
	}
	var expected string
	scanner := bufio.NewScanner(bytes.NewReader(lookup))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 3 && fields[0] == modulePath && fields[1] == version {
			expected = fields[2]
			break
		}
	}
	if expected == "" {
		return fmt.Errorf("hash of %s@%s not found in checksum database", modulePath, version)
	}

	reader, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return err
	}
	files := slices.SortedFunc(slices.Values(reader.File), func(a, b *zip.File) int {
		return strings.Compare(a.Name, b.Name)
	})
	summary := sha256.New()
	for _, file := range files {
		if strings.Contains(file.Name, "\n") {
			return fmt.Errorf("invalid file name: %q", file.Name)
		}
		content, err := readZipFile(file)
		if err != nil {
			return err
		}
		fmt.Fprintf(summary, "%x  %s\n", sha256.Sum256(content), file.Name)
	}
	actual := "h1:" + base64.StdEncoding.EncodeToString(summary.Sum(nil))
	if actual != expected {
		return fmt.Errorf("checksum mismatch: downloaded %s, checksum database %s", actual, expected)
	}
	return nil
}

func readZipFile(file *zip.File) ([]byte, error) {
	reader, err := file.Open()
	if err != nil {
		return nil, err
	}
	defer reader.Close()
	return io.ReadAll(reader)
}

// parsePackage parses the go files of the root package, generators (package main) are skipped.
func parsePackage(fileSet *token.FileSet, data []byte, version string) ([]*ast.File, error) {
	reader, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return nil, err
	}
	root := modulePath + "@" + version + "/"
	var files []*ast.File
	for _, file := range reader.File {
		name, ok := strings.CutPrefix(file.Name, root)
		if !ok || path.Dir(name) != "." || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		content, err := readZipFile(file)
		if err != nil {
			return nil, err
		}
		parsed, err := parser.ParseFile(fileSet, name, content, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		if parsed.Name.Name != packageName {
			continue
		}
		files = append(files, parsed)
	}
	if len(files) == 0 {
		return nil, errors.New("no go files found in module")
	}
	return files, nil
}

// collectTypes follows miekg/dns types_generate.go:
// every exported uint16 constant TypeX except TypePrivateRR is named X, except TypeNSAPPTR is named NSAP-PTR.
func collectTypes(fileSet *token.FileSet, files []*ast.File) (map[uint64]string, error) {
	config := types.Config{
		// Constants do not need imports, the errors of other declarations are ignored.
		Importer: importerFunc(func(path string) (*types.Package, error) {
			return nil, fmt.Errorf("import %s is skipped", path)
		}),
		Error: func(error) {},
	}
	pkg, _ := config.Check(modulePath, fileSet, files, nil)
	scope := pkg.Scope()
	table := make(map[uint64]string)
	for _, name := range scope.Names() {
		object, ok := scope.Lookup(name).(*types.Const)
		if !ok || !object.Exported() || !strings.HasPrefix(name, "Type") || name == "TypePrivateRR" {
			continue
		}
		basic, ok := object.Type().(*types.Basic)
		if !ok || basic.Kind() != types.Uint16 {
			continue
		}
		value, ok := constant.Uint64Val(object.Val())
		if !ok {
			return nil, fmt.Errorf("invalid value of %s", name)
		}
		typeName := strings.TrimPrefix(name, "Type")
		if typeName == "NSAPPTR" {
			typeName = "NSAP-PTR"
		}
		table[value] = typeName
	}
	if len(table) == 0 {
		return nil, errors.New("no DNS types found")
	}
	return table, nil
}

type importerFunc func(path string) (*types.Package, error)

func (f importerFunc) Import(path string) (*types.Package, error) {
	return f(path)
}
